import { NavLink, HeroContent } from '@/types';

export const SITE_CONFIG = {
  name: 'Apex',
  title: 'Create Next App',
  description: 'Generated by create next app',
} as const;

export const NAV_LINKS: NavLink[] = [
  { href: '#home', label: 'Home' },
  { href: '#features', label: 'Features' },
  { href: '#about', label: 'About' },
  { href: '#contact', label: 'Contact' },
];

export const HERO_CONTENT: HeroContent = {
  heading: 'Welcome to Apex',
  subheading: 'Build amazing experiences with modern web technologies',
};

export const TYPEWRITER_CONFIG = {
  headingSpeed: 100,
  subheadingSpeed: 50,
  subheadingDelay: 500,
} as const;
